config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
  }
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
  end
  scope module: :user do
    resources :informations, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
    resources :resumes, only: [:show, :edit, :destroy]
    resources :posts, only: [:index, :show, :create, :destroy] do
      resources :comments, only: [:create, :destroy] do
        resource :likes, only: [:create, :destroy]
      end
    end
    root to: 'homes#top'
  end
  devise_for :users
  resources :contacts, only: [:new, :create]
  get 'thanks', to: 'contacts#thanks'
  post 'check', to: 'contacts#check'
  get  "check" => redirect("/contacts/new")
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'search', to: 'search#search'
  get  "users" => redirect("/users/sign_up")
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, dependent: :destroy
  validates :comment, presence: true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @comments = Comment.all.page(params[:page]).per(10)
    @count = Comment.count
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_comments_path
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    post = Post.find(params[:post_id])
    @comment = current_user.comments.build(comment_params)
    @comment.post_id = post.id
    if @comment.save
      redirect_to post_path(params[:post_id])
      flash[:notice] = "コメントの投稿に成功しました。"
    else
      flash[:notice] = "コメント内容を入力してください。"
      redirect_to post_path(params[:post_id])
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user_id != current_user.id
      redirect_to new_user_session_path
    else
      @comment.destroy
      redirect_to post_path(params[:post_id])
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-2"></div>
    <div class="col-md-8 col-12 mt-5">
      <h4 class="center-position">コメント一覧(全<%= @count %>件)</h4>
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">コメント先</th>
            <th scope="col">コメント投稿者</th>
            <th scope="col" colspan="2">コメント内容</th>
            <th scope="col">投稿日時</th>
            <th scope="coi"></th>
          </tr>
        </thead>
        <tbody>
          <% @comments.each do |comment| %>
            <tr>
              <td class="td-name"><%= comment.post.title %></td>
              <td class="td-name"><%= comment.user.full_name %></td>
              <td class="td-name" colspan="2"><%= link_to comment.comment, admin_comment_path(comment.id)%></td>
              <td class="example"><%= comment.created_at.to_s(:datetime_jp) %></td>
              <td class="td-name"><%= link_to '削除', admin_comment_path(comment.id), method: :delete, id: 'delete-comment-link' + comment.id.to_s %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @comments %>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

app/views/admin/comments/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-2"></div>
    <div class="col-md-8 col-12 mt-5">
      <h4>コメント先の相談タイトル：<%= @comment.post.title %></h4>
      <p>投稿者：<%= @comment.user.full_name %></p>
      <p>投稿日：<%= @comment.created_at.to_s(:datetime_jp) %></p>
      <p><%= @comment.comment %></p>
      <p style="text-align: right;" class="pr-5"><%= link_to '削除する', admin_comment_path(@comment.id), method: :delete %></p>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>