config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
  }
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy]
    resources :comments, only: [:index, :show, :destroy]
  end
  scope module: :user do
    resources :informations, only: [:show, :edit, :update] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
    end
    resources :resumes, only: [:show, :edit, :destroy]
    resources :posts, only: [:index, :show, :create, :destroy] do
      resources :comments, only: [:create, :destroy] do
        resource :likes, only: [:create, :destroy]
      end
    end
    root to: 'homes#top'
  end
  devise_for :users
  resources :contacts, only: [:new, :create]
  get 'thanks', to: 'contacts#thanks'
  post 'check', to: 'contacts#check'
  get  "check" => redirect("/contacts/new")
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'search', to: 'search#search'
  get  "users" => redirect("/users/sign_up")
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  <!--width=device-width:横幅をデバイスのサイズに合わせる/initial-scale=1:倍率指定/shrink-to-fit=no:ios9でのView崩れ対策　 -->
    <title>AutomaticDecision</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark top-navigation">
      <div class="container">
        <h2><%= link_to "Automatic Decision", root_path, class: "navbar-brand" %></h2>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="search-form">
          <%= form_with url: search_path, method: :get, local: true do |f| %>
            <%= f.text_field :keywords, class: "search_form", placeholder: "材料で検索", class: "rounded a", size: "40x50"%>
            <%= f.submit '検索', class: "rounded btn btn-primary" %>
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "マイページ", information_path(current_user.id), class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "SNS相談", posts_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "お問い合わせ", new_contact_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white" %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "SNS相談投稿一覧", admin_posts_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_users_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "コメント一覧", admin_comments_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "text-white" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "SNS相談", posts_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "お問い合わせ", new_contact_path, class: "text-white" %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
    <nav class="navbar navbar-expand-lg navbar-dark bottom-navigation">
      <div class="container">
        <h2><%= link_to "Automatic Decision", root_path, class: "navbar-brand" %></h2>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="search-form">
          <%= form_with url: search_path, method: :get, local: true do |f| %>
            <%= f.text_field :keywords, class: "search_form", placeholder: "材料で検索", class: "rounded a", size: "40x50"%>
            <%= f.submit '検索', class: "rounded btn btn-primary" %>
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "マイページ", information_path(current_user.id), class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "SNS相談", posts_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "お問い合わせ", new_contact_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white" %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "SNS相談投稿一覧", admin_posts_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_users_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "コメント一覧", admin_comments_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "text-white" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "SNS相談", posts_path, class: "text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "お問い合わせ", new_contact_path, class: "text-white" %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </body>
</html>